### ISSUE TITLE
Installation Error at python 3.8

### ISSUE THREAD

**Issue by QuhiQuhihi** [OpenSourceRisk/ORE-SWIG#20]
I failed to install QuantExt-Python at python 3.8. Can you check the error message?
Below is error message. 
```
Collecting QuantExt-Python
  Using cached QuantExt-Python-1.8.3.3.5.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-3th0tbhv/quantext-python_d1d8ccda90ba44bbbc0a1895d9862e35/setup.py", line 204, in <module>
          save_init_posix = sysconfig._init_posix
      AttributeError: module 'distutils.sysconfig' has no attribute '_init_posix'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I used Ubuntu 22.04.1 LTS (WSL2).
Linux version 5.10.16.3-microsoft-standard-WSL2

**Comment by QuhiQuhihi** [comment]
I tried via pip install, but failed.
