### ISSUE TITLE
Can't build with python 3.6

### ISSUE THREAD

**Issue by rkapl123** [OpenSourceRisk/ORE-SWIG#8]
When running the recommended script the script fails at setup.py build (is able to build the wrappers):
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /nodefaultlib:libucrt.lib ucrt.lib /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO "/LIBPATH:C:\Program Files\Python36\libs" "/LIBPATH:C:\Program Files\Python36\PCbuild\amd64" /LIBPATH:C:\dev\boost\lib /LIBPATH:C:\dev\ORE\master\QuantLib\lib /LIBPATH:C:\dev\ORE\master\QuantExt\lib /LIBPATH:C:\dev\ORE\master\OREData\lib /LIBPATH:C:\dev\ORE\master\OREAnalytics\lib "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" "/LIBPATH:C:\Program Files (x86)\SQLXML 4.0\bin\" "/LIBPATH:C:\Program Files\SQLXML 4.0\bin\" /EXPORT:PyInit__OREAnalytics build\temp.win-amd64-3.6\Release\OREAnalytics/oreanalytics_wrap.obj /OUT:build\lib.win-amd64-3.6\OREAnalytics\_OREAnalytics.cp36-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.6\Release\OREAnalytics\_OREAnalytics.cp36-win_amd64.lib /subsystem:windows /machine:x64
LINK : fatal error LNK1181: Eingabedatei "Files\SQLXML.obj" kann nicht geöffnet werden.
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181

I've seen a very similar issue here [https://github.com/Arzaroth/python_rapidxml/issues/5](url)

my build script is
```
rem 1. Include SWIG path to the Path environment variable, e.g.
set Path=%Path%;C:\dev\swigwin

rem 2. Add PYTHON_INCLUDE and PYTHON_LIB variables to the system environment, e.g. 
set PYTHON_INCLUDE="C:\Program Files\Python36\include"
set PYTHON_LIB="C:\Program Files\Python36\libs"

rem 3. Add BOOST_ROOT and BOOST_LIBRARYDIR variables to the system environment, e.g. 
set BOOST_ROOT=C:\dev\boost
set BOOST_LIBRARYDIR=C:\dev\boost\lib

rem 4. Add ORE_DIR and QL_DIR variables to the system environment, e.g.
set ORE_DIR=C:\dev\ORE\master
set QL_DIR=C:\dev\ORE\master\QuantLib

rem 5. Change to directory OREAnalytics-SWIG/Python and run the following
rem    python scripts to build and install ORE Analytics Python module:
cd OREAnalytics-SWIG\Python
python setup.py wrap
python setup.py build
```

**Comment by jmelo11** [comment]
The lib is available via pip. Does it help you?

**Comment by laurent101** [comment]
Hi jmelo11, you're saying ORE-SWIG Python can be installed via pip? How? Thanks

**Comment by jmelo11** [comment]
yep. pip install QuantExt-Python

**Comment by fordesmith** [comment]
Hi,
I receive a lot of 'deprecated' error messages when I try to compile ORE-SWIG. I also tried 

pip3 install QuantExt-Python

Collecting QuantExt-Python
  Using cached QuantExt-Python-1.8.3.3.5.tar.gz (1.0 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.8/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/v3/b1m57r514jg5pc6clm_dfnlc0000gn/T/pip-install-veymxks3/quantext-python/setup.py'"'"'; __file__='"'"'/private/var/folders/v3/b1m57r514jg5pc6clm_dfnlc0000gn/T/pip-install-veymxks3/quantext-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/v3/b1m57r514jg5pc6clm_dfnlc0000gn/T/pip-pip-egg-info-jxwekt3t
         cwd: /private/var/folders/v3/b1m57r514jg5pc6clm_dfnlc0000gn/T/pip-install-veymxks3/quantext-python/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/v3/b1m57r514jg5pc6clm_dfnlc0000gn/T/pip-install-veymxks3/quantext-python/setup.py", line 251, in <module>
        license          = codecs.open('../../LICENSE.TXT','r+',
      File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/codecs.py", line 905, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '../../LICENSE.TXT'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by SamRech** [comment]
As far as i tried it only worked with Python 3.7.9. Does it work with another version by pip as well?

**Comment by rkapl123** [comment]
This is so old that it's not relevant anymore.
